version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - squash-tm-db:/var/lib/mysql/data
  main:
    image: apache/openmeetings:${OM_TAG}
    restart: always
    ports:
      - 5443:5443
      - 8888:8888
    environment:
      - OM_DB_HOST=db
volumes:
  squash-tm-db:
